### ISSUE TITLE
Cancel invitation needs a workflow

### ISSUE THREAD

**Issue by withanage** [craft-oa/ui-library#15]
[Screencast from 20.08.2024 17:14:25.webm](https://github.com/user-attachments/assets/612d3de2-9aee-4887-9fa3-f68db42a0492)

**Comment by withanage** [comment]
![image1](https://github.com/user-attachments/assets/af23f861-4375-4af8-a1e9-4d5a16bebee0)
![image2](https://github.com/user-attachments/assets/8051145c-4a39-4876-be42-9f3d154e9f9f)

**Comment by ipula** [comment]
done, need to do the necessary styling, need to check with Jarda

**Comment by withanage** [comment]
@ipula  may be i would prioratize this tomorrow. I think we also have the success message too, If I remember correctly.
