### ISSUE TITLE
Names shouldn't be concatenated client-side

### ISSUE THREAD

**Issue by asmecher** [craft-oa/ui-library#17]
We shouldn't be concatenating names in [this code](https://github.com/ipula/ui-library/blob/c40baa1b78cab5de5ffb3543ca98e52181cd7737/src/managers/InvitationManager/InvitationManagerStore.js#L68). Names are built in different ways for different languages, and the logic shouldn't be replicated multiple times in the system.

We should consider either having the API provide full names built by a common function in PHP, or if the front end needs to be able to do this, then there should be a common feature to do it in JS.

I checked with Jarda and he prefers name concatenation server-side, with the full name provided by the API. I agree.

**Comment by withanage** [comment]
Related PRS

- https://github.com/pkp/pkp-lib/pull/9796

**Comment by asmecher** [comment]
@withanage, is this actually resolved? It looks like the name concatenation is still happening in the same place in what I think is the most recent branch: https://github.com/ipula/ui-library/blob/edfa76db05fc461eeeeb99007893afe2674133c7/src/managers/InvitationManager/InvitationManagerStore.js#L73

**Comment by ipula** [comment]
@asmecher there is another one I fixed. I will talk about this with Dimithri
