### ISSUE TITLE
When entered, emails should be shown in the invitation list

### ISSUE THREAD

**Issue by asmecher** [craft-oa/ui-library#21]
When an email address exists for a user, it should be shown in the invitation list.

From Devika:
> In the invitation table, the user’s email isn’t currently visible, which is crucial for contact between the editor or JM and the user. The UX/UI mockups do include the email.

**Comment by defstat** [comment]
@Devika008, should we display the email that the invitation was dispatched to, or the email of the existing user? These could be different, as the user might change their account's email after the invitation is sent.

I'll proceed with implementing it to return the email to which the invitation was originally sent, but if there is any objections, I can change it.

**Comment by withanage** [comment]
### Current status
![Screenshot from 2024-09-26 13-16-39](https://github.com/user-attachments/assets/577a3a16-6e43-4b26-bf9d-92db89977dd4)

**Comment by defstat** [comment]
@withanage this has been implemented in the backoffice. If you need anything else regarding this, ping me here.

**Comment by withanage** [comment]
@defstat  thanks for confirmation!
