### ISSUE TITLE
Edit invitation - changes to the wording

### ISSUE THREAD

**Issue by withanage** [craft-oa/ui-library#22]
- The "view" button has been changed to "edit"

![image1](https://github.com/user-attachments/assets/b37efebb-dca5-4a7d-9121-f0fa968f6ed8)

- When "edit" is clicked following screen will be shown with clear indications about what will happen when you modify an invitation

![image2](https://github.com/user-attachments/assets/9eea6216-dac5-4095-a2b5-fa5a77ac4e42)

- On clicking modify information you can edit the details of existing information

![image3](https://github.com/user-attachments/assets/1d35bd70-ab5c-415d-8855-d5b1016e895d)

- you can also add another role 

![image4](https://github.com/user-attachments/assets/ecc402d0-2ecc-4cfc-a39e-5eb5f0ed31cc)

**Comment by ipula** [comment]
done
