### ISSUE TITLE
Userroles in the email is not yet filled

### ISSUE THREAD

**Issue by withanage** [craft-oa/ui-library#23]
![Screenshot from 2024-09-10 13-54-35](https://github.com/user-attachments/assets/0a6dc6ac-7513-43a5-9366-303c18851ab6)

**Comment by ipula** [comment]
@withanage this should be on Dimithri's development

**Comment by defstat** [comment]
@withanage I see that this is the actual email that OJS will send when an invitation is dispatched. I can't reproduce it though. 

The email I am getting for non existing users is ![Image](https://github.com/user-attachments/assets/15426b59-aa6e-473c-ac1b-1d2b62b21b9d)

For existing users is the following: ![Image](https://github.com/user-attachments/assets/e2c9e4fe-0115-4fdd-bfc1-6792b98d2d7e)


Is there a specific case that this is happening?

**Comment by withanage** [comment]
@defstat  no this is the general inviation. 


@ipula   can you may be check this again locally  ?

**Comment by ipula** [comment]
@withanage may its on our template. May be its updated?

**Comment by withanage** [comment]
@ipula  inviteename is also not filled in the server template. Can you check this also  locally ?


 there is also another template which has this error![Image](https://github.com/user-attachments/assets/79d67b91-3921-4890-ae51-2b47206262d1)

**Comment by withanage** [comment]
@ipula  I have tested the server with your newest updates. The template variables seems to be still not working.

![Screenshot from 2024-10-01 11-28-13](https://github.com/user-attachments/assets/24030961-44d9-46b3-b10a-502411e22759)

**Comment by withanage** [comment]
![Screenshot from 2024-10-02 16-12-49](https://github.com/user-attachments/assets/9f1abebe-8540-4499-a551-cf83bc2ed2cb)

**Comment by ipula** [comment]
![Image](https://github.com/user-attachments/assets/6c4937a4-da3e-405b-840e-9014217b8903)

In my local now its working with new database and new pull

**Comment by withanage** [comment]
@ipula 

if we could check the server again, that will be  good.
