### ISSUE TITLE
ui.js  with locale  keys does not get created due to policies  for anonymous users

### ISSUE THREAD

**Issue by withanage** [craft-oa/ui-library#29]
### Issue

https://craft-test.online/9658/index.php/publicknowledge/en/invitation/accept?id=4&key=biSQvg

### Current findings
-  Reproducible for non-installed systems, when you use an older config.inc.php file
-

**Comment by jardakotesovec** [comment]
Would be very interested why this is happening on your server, there is no access restriction on the ui.js

**Comment by withanage** [comment]
FYI @jardakotesovec 


### Reason


- Since OJS 3.4, the setting `allowed_hosts` is a mandatory field in the file `config.inc.php`.
- Adter OJS 3.4 ,  the following setting `allowed_hosts = ‘[\’localhost\‘]’ is already included in the `config.TEMPLATE.inc.php` file , therefore it would not  create an unauthorized error  for not logged  users.
- If a server administrator moves an older config.file from  an older installation prior to OJS 3.4,    `allowed_hosts = ‘’` or the correct host setting must be added to the `config.inc.php` file. Recommended  is the exact host name as described in the `config.TEMPLATE.inc.php

> ; Restrict the list of allowed hosts to prevent HOST header injection.
> ; See docs/README.md for more details. The list should be JSON-formatted.
> ; An empty string indicates that all hosts should be trusted (not recommended!)
> ; Example:
> ; allowed_hosts = '["myjournal.tld", "anotherjournal.tld", "mylibrary.tld"]'
> allowed_hosts = "[\"localhost\"]"
> 
>
