### ISSUE TITLE
When accepting invitation the cancel button does not do anything.

### ISSUE THREAD

**Issue by jardakotesovec** [craft-oa/ui-library#68]
![Screenshot 2024-10-22 at 12 23 26](https://github.com/user-attachments/assets/0f1d699b-66c9-45d4-91cb-e6a7b7a1dfdb)

**Comment by jardakotesovec** [comment]
@ipula implemented dialog which let user to get back to submisions. To be reviewed by @Devika008

**Comment by Devika008** [comment]
Hi @jardakotesovec @withanage and @ipula 

Here's my suggestion on how best to go ahead in this scenario

# Proposed UX Flow for the Cancel Button

1. User clicks the Cancel button.
2. Trigger a confirmation modal (pop-up) with clear messaging to explain the consequence of canceling.
3. Offer clear actions: "Cancel Invitation Process" or "Go Back."

## Confirmation Modal Design
Modal Title:
"Cancel Role Invitation Process?"
Message:
"Are you sure you want to cancel?
Canceling now will stop the role acceptance process, and you’ll need to restart from the invitation email to accept the role again. If you’re already a user, you’ll be taken back to the dashboard. If not, you’ll need to access the invitation email to start the process again."

Action Buttons:
[Cancel Invitation Process] and [Go Back]

## Post-Cancel Behavior Based on User Type

If the User Is Not Logged In:
Redirect them to a landing page with a message:
"You’ve canceled the process. Please restart from your invitation email if you wish to accept the role."

If the User Is Logged In (OJS Dashboard):
Redirect them to the OJS Dashboard with a toast notification:
"Invitation process canceled. You can restart the process anytime from your email invitation."
