### ISSUE TITLE
When role is being removed - its removed after acceptation

### ISSUE THREAD

**Issue by jardakotesovec** [craft-oa/ui-library#69]
Role removal has to happen when the invitation is created, and user would be informed that it happened. There is nothing to accept there.

**Comment by defstat** [comment]
@jardakotesovec can you describe this issue a little bit more?

**Comment by jardakotesovec** [comment]
This issue was resolved by the change in the workflow discussed on today meeting, where removing role will be handled as immediate action via new api. So removing roles won't be part of the invitation process.
