### ISSUE TITLE
Both primary and other languages are required for first name, last name and affiliation

### ISSUE THREAD

**Issue by jardakotesovec** [craft-oa/ui-library#70]
I think that the logic we follow on other places is to require only primary language. This needs to be adjusted on server side validation.

**Comment by jardakotesovec** [comment]
![Screenshot 2024-10-22 at 12 28 44](https://github.com/user-attachments/assets/591a79e4-f452-4fd6-b828-81eb895d5854)

**Comment by defstat** [comment]
@ipula can you confirm whether this is already covered, or there is something else needed?

**Comment by jardakotesovec** [comment]
This description is not accurate. We want to basically follow the requirements that we currently have on user profile. Which is that the first name and country are required. And there are required only for the primary locale (it would be good to check how the locale is determined in current implementation.

This requires adjustments both client and server side.
