### ISSUE TITLE
Good error message should be displayed when invitation is being accepted while different user is logged in

### ISSUE THREAD

**Issue by jardakotesovec** [craft-oa/ui-library#71]
![Screenshot 2024-10-22 at 12 31 10](https://github.com/user-attachments/assets/5074e45e-2ea6-436f-98bf-b7556baf9a47)

**Comment by Devika008** [comment]
Hello @jardakotesovec and @withanage 

You can use this messaging and error panel for the above function

![image](https://github.com/user-attachments/assets/42782e6a-2215-454c-9596-c6247b4ebee6)

Error Message: "Invitation not accepted – You're logged in as a different user."

Explanation/Guidance:
"Please log out and sign in with the correct account to accept this invitation."

Action Button:
[Log Out] and [Cancel]

**Comment by ipula** [comment]
@Devika008 what happen I click cancel?

**Comment by Devika008** [comment]
@ipula when you click cancel, it should take you to the OJS Submission dashboard - the one you see as a user you have logged in
