### ISSUE TITLE
Do we want to indicate to the user he has no role?

### ISSUE THREAD

**Issue by jardakotesovec** [craft-oa/ui-library#73]
Because roles might come with future date - user can have account without roles. In that case we just show the Profile. Which is ok.. but might not be clear whats going on.

![Screenshot 2024-10-22 at 12 59 57](https://github.com/user-attachments/assets/c1c1c597-09f3-44fe-a8fb-a1a6b8e6a3b3)

**Comment by jardakotesovec** [comment]
@devika advised to indicate in such scenario that there is role coming in the future. So the user is not asking editor whats going on.

**Comment by Devika008** [comment]
@jardakotesovec and @withanage 

We can show the following text as an indication on top of the profile page

![image](https://github.com/user-attachments/assets/6c066d7b-3aa9-439b-844a-43832d63b44b)

@jardakotesovec this is the same element that we use to indicate status on the workflow page

Informational Banner Message:
"Your role is scheduled to begin on [Start Date]."
Subtext:
"Until then, you can review and update your profile. If you believe this is an error, please contact journal administrator."

**Comment by withanage** [comment]
@ipula  did we have this already ?
