### ISSUE TITLE
Handle removing roles as immediate action via new endpoint

### ISSUE THREAD

**Issue by jardakotesovec** [craft-oa/ui-library#75]
On meeting we agreed on handle the removing the role outside of the invitation process. Main reason is that for removing role does not make much sense to create new invitation as we need to remove the role without accepting the invitation.

Instead we use the same UI, and when users clicks on 'Remove Role' he will be presented with confirmation dialog to confirm role removal and new endpoint for removing roles would be used to immediately remove that role.

After role is removed, the list of roles would get refreshed and that role would not be displayed there anymore.

**Comment by ewhanson** [comment]
@jardakotesovec, in the call we discussed that an email should also be sent at this point. Does that email already exist or does a new one need to be created? Sending it is trivial, just need to know if I should implement an existing one, write a new one, or leave a TODO in the API endpoint to handle it?

**Comment by jardakotesovec** [comment]
@ewhanson I think there is just one new template for it created so far - when sending out invitation. But @defstat will know better, I think he did add the template for invitations.

So my best guess that for removing we would want new template, specifically just for removing, but lets double check with @defstat whether he might have already created something.

**Comment by defstat** [comment]
@ewhanson @jardakotesovec  yes I had the "removed roles" displayed in the specific invitation email. So removing them from there, leaves that open for a new emailTemplate and separate process of sending it upon removal of the UserUserGroup.

**Comment by ewhanson** [comment]
PRs:

- `pkp-lib`: pkp/pkp-lib#10563

**Comment by ewhanson** [comment]
Hey @taslangraham, could you have a look at these PRs? Thanks!

PRs:

- `pkp-lib`: pkp/pkp-lib#10563
- `ojs`: pkp/ojs#4499
- `omp`: pkp/omp#1747
- `ops`: pkp/ops#801

**Comment by taslangraham** [comment]
@ewhanson PRs look good! I've reviewed and approved each.

**Comment by ewhanson** [comment]
Thanks, @taslangraham, merged!
